version: '3.1'

networks:
  network-postgresql:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.20.239.0/24

services:
  postgresql:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_PASSWORD: "senhapostgresql"
    ports:
      - "15432:5432"
    volumes:
      - './bancos:/var/lib/postgresql/data:rw'
    networks:
      - network-postgresql
      
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "mail@google.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "16543:80"
    depends_on:
      - postgresql
    networks:
      - network-postgresql